### PR TITLE
Update to version 1.7.1

### PR DESCRIPTION
**Pull request by joshuag1000**
https://github.com/raspberrypi/rpi-imager/releases/tag/v1.7.1

### CODE REVIEW

**Comment by hfiguiere** [comment]
the patch fail to apply. Did you try to build it locally first?

**Comment by joshuag1000** [comment]
> the patch fail to apply. Did you try to build it locally first?

I'm going to rebuild it later to see what caused the patch to fail.

**Comment by joshuag1000** [comment]
> Build [77205 successful](https://flathub.org/builds/#/builders/32/builds/77205)
> To test this build, install it from the testing repository:
> ```
> flatpak install --user https://dl.flathub.org/build-repo/75074/org.raspberrypi.rpi-imager.flatpakref
> ```
> 

As seen here it should be good to go. Going to do some runtime tests myself later.

**Comment by joshuag1000** [comment]
I have done some runtime tests and i have discovered that when you use the setting option to modify the config.txt for you it would fail due to flatpaks permissions. 
I have added access to:
/mnt
/media
/run/media
Which should cover the locations where a MicroSD card could be mounted automatically.

**Comment by ghisvail** [comment]
We should probably only add `--filesystem=/run/media` (and maybe `--filesystem=/media`). I am not sure about `/mnt` since it's a general mount point, which we'd rather want not to expose to the sandbox as a RW.

**Comment by joshuag1000** [comment]
> We should probably only add `--filesystem=/run/media` (and maybe `--filesystem=/media`). I am not sure about `/mnt` since it's a general mount point for which we'd rather avoid exposure to the sandbox in RW.

Maybe? I know /run/media is used by my system (fedora 35) and i think /media is used by ubuntu. Adding /mnt just sounded like a good idea to have incase it is used by some other os.
At the end of the day its up to whoever has write access to the repo.

**Comment by joshuag1000** [comment]
Its worth noting i have Allow edits by maintainers ON so if whoever has write access decides to not include /mnt then they can just create a commit and remove it.

**Comment by ghisvail** [comment]
> Maybe? I know /run/media is used by my system (fedora 35) and i think /media is used by ubuntu.

Ok, let's start with just `/run/media` and `/media` then.

> Adding /mnt just sounded like a good idea to have incase it is used by some other os.

Others may use `/opt` as well. I am sur those users would know how to launch this flatpak with additional permissions.

Thanks for taking care of this update, I'll do the edits and merge.

**Comment by ghisvail** [comment]
bot, build

**Comment by hfiguiere** [comment]
`/media` and `/run/media` are the permission for removable like SD Card. anything else is against the standard.

**Comment by joshuag1000** [comment]
> `/media` and `/run/media` are the permission for removable like SD Card. anything else is against the standard.

Good to know

**Comment by joshuag1000** [comment]
Just a quick question how long does it take flathub to make the update available?

**Comment by hfiguiere** [comment]
by default, a few hours.

**Comment by joshuag1000** [comment]
Reason i ask is because the docs say 3 hours.
Lol I'm just impatient. I just checked the build servers and its build compiled now.
https://flathub.org/builds/#/builders/29/builds/40750

**Comment by hfiguiere** [comment]
I published it "manually" (it's one click with permissions) so it should be here now.

**Pull request merged**
