### PR TITLE
New upstream 1.5

### PR DESCRIPTION
**Pull request by hfiguiere**
- Update SDK

### CODE REVIEW

**Comment by hfiguiere** [comment]
This new version include privacy invading telemetry. I haven't patched it yet.

**Comment by hfiguiere** [comment]
This next build will have telemetry disabled by default. Users can still opt-in.

**Comment by ghisvail** [comment]
Looks good to me. Have you got a screenshot of the new release of the app working locally?

**Comment by hfiguiere** [comment]
image

**Comment by ghisvail** [comment]
Brilliant. Thank you for your contribution.

**Pull request merged**
